//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uniplat.UniplatProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReqDebit", Namespace="http://schemas.datacontract.org/2004/07/UniplatServiceWCF")]
    [System.SerializableAttribute()]
    public partial class ReqDebit : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HashField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MSISDNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperatorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartnerCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Hash {
            get {
                return this.HashField;
            }
            set {
                if ((object.ReferenceEquals(this.HashField, value) != true)) {
                    this.HashField = value;
                    this.RaisePropertyChanged("Hash");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MSISDN {
            get {
                return this.MSISDNField;
            }
            set {
                if ((object.ReferenceEquals(this.MSISDNField, value) != true)) {
                    this.MSISDNField = value;
                    this.RaisePropertyChanged("MSISDN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OperatorCode {
            get {
                return this.OperatorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.OperatorCodeField, value) != true)) {
                    this.OperatorCodeField = value;
                    this.RaisePropertyChanged("OperatorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartnerCode {
            get {
                return this.PartnerCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PartnerCodeField, value) != true)) {
                    this.PartnerCodeField = value;
                    this.RaisePropertyChanged("PartnerCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentId {
            get {
                return this.PaymentIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentIdField, value) != true)) {
                    this.PaymentIdField = value;
                    this.RaisePropertyChanged("PaymentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentNumber {
            get {
                return this.PaymentNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentNumberField, value) != true)) {
                    this.PaymentNumberField = value;
                    this.RaisePropertyChanged("PaymentNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceId {
            get {
                return this.ServiceIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceIdField, value) != true)) {
                    this.ServiceIdField = value;
                    this.RaisePropertyChanged("ServiceId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Resp", Namespace="http://schemas.datacontract.org/2004/07/UniplatServiceWCF")]
    [System.SerializableAttribute()]
    public partial class Resp : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ResultCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultcomentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentId {
            get {
                return this.PaymentIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentIdField, value) != true)) {
                    this.PaymentIdField = value;
                    this.RaisePropertyChanged("PaymentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResultCode {
            get {
                return this.ResultCodeField;
            }
            set {
                if ((this.ResultCodeField.Equals(value) != true)) {
                    this.ResultCodeField = value;
                    this.RaisePropertyChanged("ResultCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Resultcoment {
            get {
                return this.ResultcomentField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultcomentField, value) != true)) {
                    this.ResultcomentField = value;
                    this.RaisePropertyChanged("Resultcoment");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReqState", Namespace="http://schemas.datacontract.org/2004/07/UniplatServiceWCF")]
    [System.SerializableAttribute()]
    public partial class ReqState : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HashField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartnerCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Hash {
            get {
                return this.HashField;
            }
            set {
                if ((object.ReferenceEquals(this.HashField, value) != true)) {
                    this.HashField = value;
                    this.RaisePropertyChanged("Hash");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartnerCode {
            get {
                return this.PartnerCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PartnerCodeField, value) != true)) {
                    this.PartnerCodeField = value;
                    this.RaisePropertyChanged("PartnerCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentId {
            get {
                return this.PaymentIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentIdField, value) != true)) {
                    this.PaymentIdField = value;
                    this.RaisePropertyChanged("PaymentId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UniplatProxy.IUniplatService")]
    public interface IUniplatService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUniplatService/DebitMoney", ReplyAction="http://tempuri.org/IUniplatService/DebitMoneyResponse")]
        Uniplat.UniplatProxy.Resp DebitMoney(Uniplat.UniplatProxy.ReqDebit request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUniplatService/GetDebitState", ReplyAction="http://tempuri.org/IUniplatService/GetDebitStateResponse")]
        Uniplat.UniplatProxy.Resp GetDebitState(Uniplat.UniplatProxy.ReqState request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUniplatServiceChannel : Uniplat.UniplatProxy.IUniplatService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UniplatServiceClient : System.ServiceModel.ClientBase<Uniplat.UniplatProxy.IUniplatService>, Uniplat.UniplatProxy.IUniplatService {
        
        public UniplatServiceClient() {
        }
        
        public UniplatServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UniplatServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UniplatServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UniplatServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Uniplat.UniplatProxy.Resp DebitMoney(Uniplat.UniplatProxy.ReqDebit request) {
            return base.Channel.DebitMoney(request);
        }
        
        public Uniplat.UniplatProxy.Resp GetDebitState(Uniplat.UniplatProxy.ReqState request) {
            return base.Channel.GetDebitState(request);
        }
    }
}
