/*
   Copyright 2006-2017 Cryptany, Inc.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cryptany.Core.Services.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:3326/Aggregation/Aggregator.asmx")]
        public string CryptanyCore_AggregatorWebService_Aggregator {
            get {
                return ((string)(this["CryptanyCore_AggregatorWebService_Aggregator"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:1933/AggregationClient/MessageReceiver.asmx")]
        public string CryptanyCore_AggregationClientWS_MessageReceiver {
            get {
                return ((string)(this["CryptanyCore_AggregationClientWS_MessageReceiver"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:3483/AggregationClient/MessageReceiver.asmx")]
        public string CryptanyCore_AggregationClient_MessageReceiver {
            get {
                return ((string)(this["CryptanyCore_AggregationClient_MessageReceiver"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Неверный формат данных. Не удаётся преобразовать данные к требуемому типу.")]
        public string MSG_WrongDataItemFormat {
            get {
                return ((string)(this["MSG_WrongDataItemFormat"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Неверное количество элементов RuleData для данного типа правила.")]
        public string MSG_WrongNumberOfRulesDataItems {
            get {
                return ((string)(this["MSG_WrongNumberOfRulesDataItems"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://dev.mobster.ru/dev/footballws/subscriptions.asmx")]
        public string CryptanyCore_ru_mobster_dev_subscriptions {
            get {
                return ((string)(this["CryptanyCore_ru_mobster_dev_subscriptions"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Spasibo za pokupku! Skachaite vash zakaz zdes\': ")]
        public string LinkToContentMessage {
            get {
                return ((string)(this["LinkToContentMessage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://devsvr2/dev/foundation3/subscriptions/wssubscriptions.asmx")]
        public string CryptanyCore_MtClubSubsbriptions_wsSubscriptions {
            get {
                return ((string)(this["CryptanyCore_MtClubSubsbriptions_wsSubscriptions"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://devsvr2/dev/foundation3/subscriptions/wssubscriptions.asmx")]
        public string CryptanyCore_MtClubSubsbriptions_wsSubscriptions_temp {
            get {
                return ((string)(this["CryptanyCore_MtClubSubsbriptions_wsSubscriptions_temp"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://dl2.mobster.ru/ContentLinkWS/Service.asmx")]
        public string CryptanyCore_ru_mobster_dl2_Service {
            get {
                return ((string)(this["CryptanyCore_ru_mobster_dl2_Service"]));
            }
        }
    }
}
